### ISSUE TITLE
Default H2 DB config doesn't work

### ISSUE THREAD

**Issue by gabriel-fallen** [webdsl/webdsl-editor#1]
With the default `application.ini` like this
```
db=h2
dbfile=HelloWeb.db
dbmode=create-drop
```
I get an error `org.h2.jdbc.JdbcSQLNonTransientConnectionException: A file path that is implicitly relative to the current working directory is not allowed in the database URL "jdbc:h2:HelloWeb.db;FILE_LOCK=NO". Use an absolute path, ~/name, ./name, or the baseDir setting instead.`

This way it works:
```
db=h2
dbfile=./HelloWeb.db
dbmode=create-drop
```

**Comment by dgroenewegen** [comment]
Thanks for the report, I have added the ./ to the default location https://github.com/webdsl/webdsl-editor/commit/2af1b6d45a6dba1e2d6d272dc040d929de16ad3d

**Comment by gabriel-fallen** [comment]
Thanks for the fast fix! :smiley:
